---
- name: "Install app nodejs"
  hosts: aula
  become: yes
  vars:
   path_app: /usr/app
   app_name: app_node2-master
  tasks:
    - name: Linux - Install unzip
      package:
        name:
          - unzip
        state: present

    - name: Create dir app
      file:
        path: "{{path_app}}"
        state: directory

    - name: Download and Save App
      unarchive:
        src: https://github.com/bgsouza/app_node2/archive/master.zip
        dest: "{{path_app}}"
        remote_src: yes
      register: download_app

    - name: Install "pm2" node.js package globally.
      npm:
        name: pm2
        global: yes
 
    - name: Install packages based on package.json.
      npm:
        path: "{{path_app}}/{{app_name}}"
      when: download_app is success
      register: install_packages_app
      
    - name: Iniciando a aplicação
      command: pm2 start {{path_app}}/{{app_name}}/app.js
      when: install_packages_app is success